language: node_js

node_js:
    - 10

cache: npm

install:
    - npm install

script:
    - commitlint-travis
    - npm run test

branches:
    except:
        - '/^v\d+\.\d+\.\d+$/'

jobs:
    include:
        - stage: test
          script:
              - npm run test
        - stage: deploy
          if: branch == master && !fork
          node_js: '10'
          script:
              - npm install -g semantic-release@^15
              - semantic-release

after_failure: "cat /home/travis/build/MarcLoupias/md-file-converter/npm-debug.log"
